# Site settings
title: KP's Laboratory
email: kapileshwarsingh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  KP's Laboratory is my blog where I publish the results of my the technological experiments
  and the scope is not limited to math, performance and the Linux Kernel

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sinkap.github.io" # the base hostname & protocol for your site
twitter_username: __kpsingh
github_username:  sinkap

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: Cool Option 1
    link: www.myawesomelink.com
  option2:
    name: Cool Option 2
    link: www.myawesomelink.com
  option3:
    name: Cool Option 3
    link: www.myawesomelink.com

disqus: true
disqus_shortname: 'sinkap'

# Build settings
markdown: kramdown
